### ISSUE TITLE
PostgreSQL 利用時のベーシック認証がおかしい（設定していないのに聞かれる、正しく入力してもダメ？）

### ISSUE THREAD

**Issue by dotnsf** [dotnsf/websocket-redis#18]

**Comment by dotnsf** [comment]
CodeEngine 環境だと、以下のようなエラーメッセージ: `Error: self signed certificate in certificate chain`

`var r = await dbapi.readRoom( id );` の r が以下のようになっている。CA が正しく認識されていない？？
```
{
  status: false,
  error: Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
      at TLSSocket.emit (events.js:400:28)
      at TLSSocket._finishInit (_tls_wrap.js:937:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
}
```

**Comment by dotnsf** [comment]
```
pg_params: {
    idleTimeoutMillis: 259200000,
    connectionString: 'postgres://ibm_cloud_xxxxx:xxxxxxxxxxx@xxx-xxx-xxx-xxx.xxxxxxx.databases.appdomain.cloud:32685/ibmclouddb',
    ssl: {
      ca: '-----BEGIN CERTIFICATE-----\\nxxxxxxxxxxxx\\n...\\n-----END CERTIFICATE-----',
      rejectUnauthorized: true
    }
  }
```
